<h1 align='center'> Very-Short Python Tutorial</h1><p>
<h2 align='center'> To be used as a Python Intro for the PSU EGEE 437 Class </h2>
<h3 align='center'> Paulo Soares </h3>
<h4 align='center'> Original File: 2017. Updated on Feb, 2021 </h4>   

<h2> Python Basics </h2><p>
    This is a Jupyter Notebook. The Jupyter Notebook "is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations and narrative text. Uses include: data cleaning and transformation, numerical simulation, statistical modeling, data visualization, machine learning, and much more"<p>

[Jupyter Project](https://jupyter.org) <p>

<font face="Courier" color="green" size="4"><b>References</b><p>
http://anh.cs.luc.edu//python/hands-on/3.1/handsonHtml/index.html#<p>


Hint: To run a cell hit SHIFT+ENTER

<h3>0. Load Required Packages</h3>

In [32]:
import numpy as np # "NumPy is the fundamental package for scientific computing with Python." np is how you call the package
import matplotlib.pyplot as plt # "Matplotlib is a Python 2D plotting library which produces publication quality figures..."
import sys #Information about the system

%pylab inline
#Graphs are shown below the code cell instead in a new window.

Populating the interactive namespace from numpy and matplotlib


In [33]:
print (sys.version) # Checks which version of Python you're using (and Anaconda, if you're using it).

3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]


<h3> 1. Functions and Types</h3><p>
    Here we start to understand the basics of Python. How to print text, and the input types recognized by the language <p>
<i> Type Options: 
<ul>
<li> int, float, long, complex </li>
<li> str </li>
<li> bytes </li>
<li> tuple </li>
<li> frozen set </li>
<li> Boolean </li>
<li> array </li>
</ul>

In [3]:
# The symbol '#' is understood as a comment
# Let's print a simple 'Hello World!'
# Note that text must be in between quotation marks ('') to be recognized as text

print('Hello World!')

Hello World!


In [2]:
# The type function tells the user what kind of input we are dealing with
# In this case we have an integer

type(5)

int

In [4]:
# And this operation returns a float - a number that is not an integer

type(7/2)

float

In [5]:
# The result of previous operation is not an integer!

type(3.5)

float

In [6]:
# Characters (text) are understood as strings - str for short

type('300')

str

In [9]:
type("Hello World")

str

In [10]:
# We can work with a list. 
# A list is composed of data points between [] and separated by commas
# Python can understand lists directly:

[2, 4, 6]

3

In [8]:
# The command len returns the number of elements within a given list:
len([2, 4, 6])

3

In [9]:
# And it can also be used for strings

len('abcd')

4

In [11]:
#Play time! Can you guess what is going on?

print(len('abcd') + len([2, 4, 6]))

7


In [12]:
# We can convert strings that are number in form of text back to numbers

int('300')

300

In [13]:
# But not the inverse

int('hello')

ValueError: invalid literal for int() with base 10: 'hello'

In [14]:
# It is even possible to convert numbers into text - strings

str(300)

'300'

In [15]:
# Self-explanatory. Try changing max for min

max(5, 11, 2)

11

<h3> 2. Simple Calculations</h3><p>

In [18]:
7+7

14

In [19]:
14*7

98

In [20]:
98-(14*7)

0

In [31]:
14/2

7.0

In [21]:
14/3

4.666666666666667

In [23]:
14//3 # Only the integer quotient

4

In [24]:
14%3 # The reminder

2

In [25]:
2^2 #this is a bitwise operation

0

In [26]:
2**2 #this is how one should write our familiar 2^2 = 4

4

<h3>3. Assigning Names to Variables</h3><p>
    Let's say we want to compute the area of a rectangle. The rectangle is 12 inches wide by 10 inches in height

In [16]:
#Width = w

w = 12

In [17]:
# Height = h

h = 10

In [22]:
#Now we calculate the area
# Note how I can print this information: area become a value once the calculation is done

area = w*h
print('The area of the rectangle is ', area,' sq. inches')  

The area of the rectangle is  120  sq. inches


In [24]:
#Suppose we wanted to calculate half of the area (for some reason):

area = (w*h)/2
print('Half of the area of the rectangle is ', area,' sq. inches') 

Half of the area of the rectangle is  60.0  sq. inches


In [26]:
# Now the last "area" is the only "area" stored in the memory
# To avoid this problem we must assign different names to the variables

area 

60.0

<h3>4. Lists and Arrays</h3>

In [27]:
a = [1,2,3,4,5,6] #this is a list

In [29]:
# A list is different from and array (a vector) - so when we multiply a list, you have:

2*a

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [34]:
# And it does not make much sense to try to elevate the list to a certain power

a**2 #you can't perform this operation with a list

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [35]:
# But we can convert the list into an array

b = np.array(a) 

In [36]:
b**2 #you can do all sorts of operations with arrays. Note there is no .** as would have .^ in Matlab

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [37]:
2*b

array([ 2,  4,  6,  8, 10, 12])

In [41]:
# Python allow us to compare the values of the array with those in the list

b == a 

array([ True,  True,  True,  True,  True,  True])

In [48]:
c = array([1,2,4,5,6,7]) #Creating an array

<h3>5. Input and Output</h3>

In [52]:
# The input command is useful when we need the user to input a value (or some values)

person = input('Enter your name: ')
print('Hello', person+'!')

Enter your name:  Paulo


Hello Paulo!


In [46]:
'''Illustrate input and print.'''

applicant = input("Enter the applicant's name: ")
interviewer = input("Enter the interviewer's name: ")
time = input("Enter the appointment time: ")
print(interviewer, "will interview", applicant, "at", time)

Enter the applicant's name: Nathanael
Enter the interviewer's name: Edson
Enter the appointment time: 5pm
Edson will interview Nathanael at 5pm


<h3>6. EGEE 437 HOMEWORK 1</h3>

<h4>Question 5</h4> <b> Copy and paste your Python code to the LaTex template to get credits!</b> <p> 
    We can convert wavelength (nm) into energy (eV). Compile a short code to answer the following questions: <p>


<b>a.</b> UV-C light is a type of shortwave light coming from the Sun that is almost totally filtered by the Earth's atmosphere. The UV-C light band ranges from 100 - 280 nm. What is the energy (in eV) contained in a UV-C ray with 150 nm?

In [ ]:
# Type your code here

wave = 

ev = 

print('what you write here?',,'nm')

<b>b.</b> What is the energy of a laser pointer that can emit 5mW of monochromatic green light (532nm)? 

In [ ]:
# Type your code here

wave = 

ev = 

print('what you write here?',,'nm')

<b>c.</b> What is the energy of a wavelength produced by a remote control? <i>"The IR signal emitted by remote controls is often around 940 nm in wavelength". </i> From [Geneva C](https://clickermart.com/blogs/news/what-is-the-wavelength-of-the-infrared-used-in-remote-controls/)

In [ ]:
# Type your code here

wave = 

ev = 

print('what you write here?',,'nm')

<h3>7. Extra Exercises - Does NOT Count towards your grade</h3>

<font size="4"><b>I - </b></font><font size="3">Create a program that asks the user to enter their name and their age. Print out a message addressed to them that tells them the year that they will turn 100 years old</font>

<font size="4"><b>II - </b></font><font size="3">Ask the user for a number. Depending on whether the number is even or odd, print out an appropriate message to the user.<p>
Hint: how does an even / odd number react differently when divided by 2?<p>

Extras:<p>

<ol type="|a|">
<li>If the number is a multiple of 4, print out a different message.</li>
<li>Ask the user for two numbers: one number to check (call it num) and one number to divide by (check). If check divides evenly into num, tell that to the user. If not, print a different appropriate message.</li></font>

<font size="4"><b>III - </b></font><font size="3"> Run the code below and try to understand what is going on. <p>
What does <b>"def"</b> stands for? </font>

In [90]:
# Code from Hands-on Python Tutorial                              
'''                                                      
String Substitution for a Mad Lib                        
Adapted from code by Kirby Urner                         
'''                                                      
                                                         
storyFormat = '''                                        
Once upon a time, deep in an ancient jungle,             
there lived a {animal}.  This {animal}                   
liked to eat {food}, but the jungle had                  
very little {food} to offer.  One day, an               
explorer found the {animal} and discovered              
it liked {food}.  The explorer took the                 
{animal} back to {city}, where it could                 
eat as much {food} as it wanted.  However,              
the {animal} became homesick, so the                    
explorer brought it back to the jungle,                 
leaving a large supply of {food}.                       
                                                        
The End                                                 
'''                                                     
                                                        
def tellStory():                                        
    userPicks = dict()                                  
    addPick('animal', userPicks)                        
    addPick('food', userPicks)                          
    addPick('city', userPicks)                          
    story = storyFormat.format(**userPicks)             
    print(story)                                        
                                                        
def addPick(cue, dictionary):                           
    '''Prompt for a user response using the cue string, 
    and place the cue-response pair in the dictionary.  
    '''                                                 
    prompt = 'Enter an example for ' + cue + ': '       
    response = input(prompt)                            
    dictionary[cue] = response                          
                                                        
tellStory()                                             
input('Press Enter to end the program.') 

Enter an example for animal: l
Enter an example for food: s
Enter an example for city: s
                                        
Once upon a time, deep in an ancient jungle,             
there lived a l.  This l                   
liked to eat s, but the jungle had                  
very little s to offer.  One day, an               
explorer found the l and discovered              
it liked s.  The explorer took the                 
l back to s, where it could                 
eat as much s as it wanted.  However,              
the l became homesick, so the                    
explorer brought it back to the jungle,                 
leaving a large supply of s.                       
                                                        
The End                                                 

Press Enter to end the program.


''

<font size="4"><b>IV - </b></font><font size="3"> Read "Hands-on Python Tutorial" until ate least item <b>1.11</b>  </font>